### ISSUE TITLE
[QUESTION] - Shader Model

### ISSUE THREAD

**Issue by ghost** [peterobbin/of_lighteffects#1]
greetings
does this require compute shader model 4.2 in order to run? i successfully compiled the application but the only thing that pops up in my screen is some kind of weird strobbing effect. i am using a macboock a1278 with an integrated intel graphics card. thank you so much!!!

**Comment by peterobbin** [comment]
@tiagomoraismorgado88  Hey! Thanks for letting me know. However, I wasn't able to re-create your problem on my machine. It shouldn't be affected by shader version. A little more info like screenshots could be more helpful. Is the GUI showing properly, or you are only seeing the strobing effect?

Anyways, I have updated the project since it is pretty old. And I can confirm that it works on Mac and Windows with latest oF (0.9.8).  Try it and let me know if you are still getting the same problem :)

**Comment by ghost** [comment]
too late. just installed debian as root on my mac today early in the morning
